import '../styles/globals.css'
import {ThemeProvider} from "@mui/material";
import {createMuiTheme} from "../theme";
import Head from "next/head";
import React from "react";

function MyApp({Component, pageProps}) {

    const theme = createMuiTheme({theme: 'muiTheme'});

    return (
        <>
            <Head>
                <title>LePorn</title>
                <meta name="description" content="Generated by create next app"/>
                <link
                    rel="icon"
                    href="https://th.bing.com/th/id/R.67bc88bb600a54112e8a669a30121273?rik=vsc22vMfmcSGfg&pid=ImgRaw&r=0"
                />
            </Head>
            <ThemeProvider theme={theme}>
                <Component {...pageProps} />
            </ThemeProvider>
        </>
    )
}

export default MyApp
